Fix task
mistandok/homework_for_students pull request #4
Opened 2024-09-23 09:25 UTC by UrakadakiRemuru

В задании по строкам (3_maximum_number_of_words) в аннотации функции возвращался bool, хотя требуется вернуть Int

2024-09-24 14:13 UTC, mistandok requested changes
Спасибо за участие и внимательность! уберите лишний комментарий, пожалуйста, и приму изменения)

2024-09-24 14:13 UTC, mistandok commented on 1_strings/3_maximum_number_of_words/main.py
> +def get_max_number_of_words_from_sentences(sentences: list[str]) -> int: #Изначально возвращался бул
привет! Спасибо большое за внимательность! 
Одно замечание: когда PR c исправлениями оформляете - не обязательно в комментах указывать, что исправили. Git все помнит. Комментарии лучше оставлять к кускам кода, которые реализуют сложную логику, и которую сложно понять без погружения в доменную область. Про это еще поговорим на курсе дальше, когда будем разбирать функции и typehinting.
Поправьте пожалуйста этот момент и приму PR :)

2024-09-27 13:33 UTC, UrakadakiRemuru commented
Здравствуйте. Комментарий убрал

2024-09-27 19:15 UTC, UrakadakiRemuru commented
Может я совсем неверно понял задание, и реализация у меня на уровне "сиди, я сам открою". На мой взгляд, 2_dict\3_task - это задание на строки с использованием регулярных выражений.

2024-09-27 19:24 UTC, UrakadakiRemuru commented
Так же в условии указана следующая формулировка "Если телефон не подходит по формату ничему перечисленному, программа выводит на печать исходный телефон, в котором оставлены только цифры.", однако тестов не присутствует для этого случая

2024-09-28 18:47 UTC, mistandok commented
> На мой взгляд, 2_dict\3_task - это задание на строки

А это я специально сделал, чтобы вы не слепо верили тому, как говорят решать задачу, а решали, опираясь на собственный опыт :) 
В реальной разработке к вам могут прийти и сказать: "сделай вот так", - а на самом деле это решение не очень оптимальное, или оно принесет проблемы в будущем. Поэтому надо уметь настоять на своем и не пытаться подстраиваться. Здорово, что обратили на это внимание

2024-09-28 19:06 UTC, mistandok approved these changes

2024-09-28 19:06 UTC, mistandok commented on 2_dicts/3_task/test.py
> +        ('1-___123-4asdf&*^ 6', '112346'),
praise: благодарю за тесты, круто, что добавили)

2024-09-28 19:07 UTC, mistandok approved these changes

2024-09-28 19:08 UTC, merged